import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
    renderTypoPresetVarsCss,
    SITE_TYPO_PRESET_CONFIG,
    SITE_TYPO_PRESET_SELECTOR,
} from "../dist/index.js";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(scriptDir, "..");
const templatePath = path.join(packageRoot, "styles/presets/site.template.css");
const outputPath = path.join(packageRoot, "styles/presets/site.css");
const header =
    "/* Generated from scripts/generate-presets.mjs. Do not edit this file directly. */";

const template = await fs.readFile(templatePath, "utf8");
const computedVars = renderTypoPresetVarsCss({
    selector: SITE_TYPO_PRESET_SELECTOR,
    config: SITE_TYPO_PRESET_CONFIG,
});

await fs.writeFile(outputPath, `${header}\n${computedVars}\n\n${template.trim()}\n`);
